changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"
